### ISSUE TITLE
'NoneType' has no len()

### ISSUE THREAD

**Issue by vherolf** [mdillehay/AdventureGame#2]
i am not sure why, but if I use latest textual and rich-pixel it works and I am a hill dwarf named lord gimli !

but if I install via your requirements.txt I get this error.

TypeError: namePicker(pseudo_classes={'enabled'}) compose() method returned an invalid result; object of type 'NoneType' has no len()

line 149 in opening.py is the problem

    def compose(self) -> ComposeResult:
        names = self.character_classes.get(TempNewChar)
        length = len(names)  # <- here
        yield OptionList(
            *[names[i] for i in range(length)], classes="height80", id="char_names"
        )
        yield Container(
            Button("Select Name", id="picker_button"), classes="nameCreatorButton"
        )

**Comment by mdillehay** [comment]
Hmmm ... just tried to recreate it on my end and didn't get the error. I will keep digging.

Did you get that error when you tried to "Submit" the name?

Also, I am still, by all accounts, very new to all of this. So I am not surprised in the least that there are issues lol!

**Comment by vherolf** [comment]
hmm maybe this one was one was on my side - I cant reproduce it anymore with the requirements.txt. 

sorry .. 

I like the idea of your project and I hope you keep up the work 
Its an awesome project
